"""
make_figures.py
---------------

Generate publication-quality figures from experiment outputs.

Figures produced:
- fig1_pr_curve.png        : Precision-recall curve for PTG and any available baselines
- fig2_budget_curve.png    : Detection rate and precision vs alert budget (top-K)
- fig3_baseline_bars.png   : PR-AUC comparison bar chart (uses error bars if robustness.json exists)
- fig4_weight_ablation.png : Horizontal bar chart of PR-AUC by (alpha, beta, gamma)

Expected project structure:
Major_Final_Code/
├── core/
│   └── make_figures.py
├── outputs/
│   ├── results/
│   │   ├── ptg_results.json
│   │   ├── baselines_fair.json
│   │   ├── robustness.json
│   │   ├── ptg_scored.csv
│   │   └── weight_ablation.csv
│   └── figures/
│       └── (generated by this script)

Usage:
    python core/make_figures.py
"""

from pathlib import Path
import json

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score, precision_recall_curve


BASE_DIR = Path(__file__).resolve().parent.parent
RESULTS_DIR = BASE_DIR / "outputs" / "results"
FIGURES_DIR = BASE_DIR / "outputs" / "figures"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "font.size": 11,
    "figure.dpi": 150,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "axes.spines.top": False,
    "axes.spines.right": False,
})

PTG_COLOR = "#0B6E4F"
ALT_COLOR = "#C44E00"
BASELINE_COLOR = "#7A7A7A"
RANDOM_COLOR = "#8A8A8A"


def load_json(filename):
    path = RESULTS_DIR / filename
    if not path.exists():
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_csv(filename):
    path = RESULTS_DIR / filename
    if not path.exists():
        return None
    return pd.read_csv(path)


def save_figure(fig, filename):
    output_path = FIGURES_DIR / filename
    fig.tight_layout()
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)
    print(f"[saved] {output_path}")


def safe_nested_get(d, *keys, default=None):
    current = d
    for key in keys:
        if not isinstance(current, dict) or key not in current:
            return default
        current = current[key]
    return current


def normalize_metric_entry(entry):
    if entry is None:
        return None

    if isinstance(entry, dict):
        mean = entry.get("mean")
        std = entry.get("std", 0.0)
        if mean is None:
            return None
        return {"mean": float(mean), "std": float(std)}

    if isinstance(entry, (int, float)):
        return {"mean": float(entry), "std": 0.0}

    return None


def fig1_pr_curve():
    """
    Precision-recall curve for PTG and any available baseline score columns in ptg_scored.csv.
    Requires a 'label' column and at least one score column.
    """
    df = load_csv("ptg_scored.csv")
    if df is None:
        print("[fig1] skip - no ptg_scored.csv")
        return False

    if "label" not in df.columns:
        print("[fig1] skip - 'label' column missing in ptg_scored.csv")
        return False

    y_true = df["label"].to_numpy()
    if len(np.unique(y_true)) < 2:
        print("[fig1] skip - labels must contain at least two classes")
        return False

    score_candidates = [
        ("score_ptg", "PTG (path-based)", PTG_COLOR),
        ("score_logreg", "LogReg", BASELINE_COLOR),
        ("score_lr", "LogReg", BASELINE_COLOR),
        ("score_ocsvm", "One-Class SVM", "#5F6B73"),
        ("score_oneclasssvm", "One-Class SVM", "#5F6B73"),
        ("score_iforest", "Isolation Forest", "#9C755F"),
        ("score_isolationforest", "Isolation Forest", "#9C755F"),
    ]

    available_scores = [(col, label, color) for col, label, color in score_candidates if col in df.columns]
    if not available_scores:
        print("[fig1] skip - no recognized score columns found in ptg_scored.csv")
        return False

    fig, ax = plt.subplots(figsize=(6.4, 5.2))
    plotted_any = False

    for column, label, color in available_scores:
        scores = df[column].to_numpy()
        if np.isnan(scores).all():
            continue

        precision_vals, recall_vals, _ = precision_recall_curve(y_true, scores)
        ap_score = average_precision_score(y_true, scores)

        linewidth = 2.4 if column == "score_ptg" else 1.8
        ax.plot(
            recall_vals,
            precision_vals,
            color=color,
            lw=linewidth,
            label=f"{label} (AP={ap_score:.3f})"
        )
        plotted_any = True

    if not plotted_any:
        plt.close(fig)
        print("[fig1] skip - all score columns are empty/NaN")
        return False

    prevalence = float(np.mean(y_true))
    ax.axhline(
        prevalence,
        ls="--",
        color=RANDOM_COLOR,
        lw=1.2,
        label=f"Random baseline ({prevalence:.4f})"
    )

    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_title("Precision-Recall Curve for Lateral Movement Detection")
    ax.set_xlim(0, 1.0)
    ax.set_ylim(0, 1.05)
    ax.legend(loc="upper right", frameon=True)

    save_figure(fig, "fig1_pr_curve.png")
    return True


def fig2_budget_curve():
    """
    Plot precision and detection rate (recall) as a function of alert budget.
    Expects ptg_results.json with a 'det_at_budget' dictionary.
    """
    ptg_results = load_json("ptg_results.json")
    if not ptg_results:
        print("[fig2] skip - no ptg_results.json")
        return False

    det_at_budget = ptg_results.get("det_at_budget", {})
    if not det_at_budget:
        print("[fig2] skip - 'det_at_budget' missing or empty in ptg_results.json")
        return False

    valid_points = []
    for key, metrics in det_at_budget.items():
        try:
            budget = int(key)
        except (TypeError, ValueError):
            continue

        if not isinstance(metrics, dict):
            continue

        detection_rate = metrics.get("detection_rate")
        precision_val = metrics.get("precision")

        if detection_rate is None or precision_val is None:
            continue

        valid_points.append((budget, float(precision_val), float(detection_rate)))

    if not valid_points:
        print("[fig2] skip - no valid budget points found")
        return False

    valid_points.sort(key=lambda x: x[0])
    budgets = [x[0] for x in valid_points]
    precisions = [x[1] for x in valid_points]
    detection_rates = [x[2] for x in valid_points]

    fig, ax1 = plt.subplots(figsize=(6.8, 5.2))

    ax1.plot(budgets, precisions, "o-", color=PTG_COLOR, lw=2.2, label="Precision")
    ax1.set_xlabel("Alert budget (Top-K)")
    ax1.set_ylabel("Precision", color=PTG_COLOR)
    ax1.set_ylim(0, 1.05)
    ax1.tick_params(axis="y", labelcolor=PTG_COLOR)

    ax2 = ax1.twinx()
    ax2.plot(budgets, detection_rates, "s--", color=ALT_COLOR, lw=2.0, label="Detection rate")
    ax2.set_ylabel("Detection rate (Recall)", color=ALT_COLOR)
    ax2.tick_params(axis="y", labelcolor=ALT_COLOR)
    upper = max(detection_rates) * 1.2 + 0.02
    upper = max(0.1, min(1.05, upper))
    ax2.set_ylim(0, upper)
    ax2.grid(False)

    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc="best", frameon=True)

    plt.title("Detection Rate and Precision vs Alert Budget")
    save_figure(fig, "fig2_budget_curve.png")
    return True


def fig3_baseline_bars():
    """
    Compare PTG against baselines using:
    - robustness.json if available (preferred, since it may contain mean/std)
    - otherwise baselines_fair.json + ptg_results.json
    """
    robustness = load_json("robustness.json")
    baselines_fair = load_json("baselines_fair.json")
    ptg_results = load_json("ptg_results.json")

    names = []
    means = []
    stds = []

    if robustness:
        candidate_order = [
            ("PTG", safe_nested_get(robustness, "PTG", "PR_AUC")),
            ("LogReg\n(supervised)", safe_nested_get(robustness, "LogisticRegression_supervised", "PR_AUC")),
            ("One-Class\nSVM", safe_nested_get(robustness, "OneClassSVM", "PR_AUC")),
            ("Isolation\nForest", safe_nested_get(robustness, "IsolationForest", "PR_AUC")),
        ]

        for name, raw_entry in candidate_order:
            metric = normalize_metric_entry(raw_entry)
            if metric is not None:
                names.append(name)
                means.append(metric["mean"])
                stds.append(metric["std"])

    else:
        ptg_auc = ptg_results.get("PR_AUC") if ptg_results else None
        if ptg_auc is not None:
            names.append("PTG")
            means.append(float(ptg_auc))
            stds.append(0.0)

        if baselines_fair:
            fallback_order = [
                ("LogReg\n(supervised)", safe_nested_get(baselines_fair, "LogisticRegression_temporal", "PR_AUC")),
                ("One-Class\nSVM", safe_nested_get(baselines_fair, "OneClassSVM", "PR_AUC")),
                ("Isolation\nForest", safe_nested_get(baselines_fair, "IsolationForest", "PR_AUC")),
            ]
            for name, raw_auc in fallback_order:
                metric = normalize_metric_entry(raw_auc)
                if metric is not None:
                    names.append(name)
                    means.append(metric["mean"])
                    stds.append(metric["std"])

    if not names:
        print("[fig3] skip - no baseline comparison data found")
        return False

    colors = [PTG_COLOR if name == "PTG" else BASELINE_COLOR for name in names]

    fig, ax = plt.subplots(figsize=(7.0, 5.2))
    bars = ax.bar(
        names,
        means,
        yerr=stds,
        capsize=5,
        color=colors,
        edgecolor="black",
        linewidth=0.6
    )

    label_offset = max(0.01, max(means) * 0.04)
    for bar, mean_val in zip(bars, means):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            mean_val + label_offset,
            f"{mean_val:.3f}",
            ha="center",
            va="bottom",
            fontsize=9
        )

    random_floor = None
    if baselines_fair:
        random_floor = baselines_fair.get("prevalence_PR_AUC_floor")

    if random_floor is not None:
        ax.axhline(
            float(random_floor),
            linestyle="--",
            color="red",
            linewidth=1.1,
            label=f"Random baseline ({float(random_floor):.4f})"
        )
        ax.legend(loc="best", frameon=True)

    max_bar_height = max(m + s for m, s in zip(means, stds))
    y_upper = max_bar_height + max(0.03, max_bar_height * 0.12)
    ax.set_ylabel("PR-AUC (Average Precision)")
    ax.set_title("Detection Performance: PTG vs Baselines")
    ax.set_ylim(0, y_upper)

    save_figure(fig, "fig3_baseline_bars.png")
    return True


def fig4_weight_ablation():
    """
    Horizontal bar chart of PR-AUC by (alpha, beta, gamma).
    Expects weight_ablation.csv with columns: alpha, beta, gamma, PR_AUC
    """
    wa = load_csv("weight_ablation.csv")
    if wa is None:
        print("[fig4] skip - no weight_ablation.csv")
        return False

    required_columns = {"alpha", "beta", "gamma", "PR_AUC"}
    if not required_columns.issubset(wa.columns):
        missing = sorted(required_columns - set(wa.columns))
        print(f"[fig4] skip - missing columns in weight_ablation.csv: {missing}")
        return False

    wa = wa.copy()
    wa = wa.sort_values("PR_AUC", ascending=True)

    labels = [
        f"({row.alpha}, {row.beta}, {row.gamma})"
        for row in wa.itertuples(index=False)
    ]
    values = wa["PR_AUC"].to_numpy()

    max_value = float(np.max(values))
    colors = [ALT_COLOR if np.isclose(v, max_value) else PTG_COLOR for v in values]

    fig, ax = plt.subplots(figsize=(7.4, 4.8))
    bars = ax.barh(labels, values, color=colors, edgecolor="black", linewidth=0.5)

    x_offset = max(0.003, max_value * 0.01)
    for bar, value in zip(bars, values):
        ax.text(
            value + x_offset,
            bar.get_y() + bar.get_height() / 2,
            f"{value:.3f}",
            va="center",
            fontsize=9
        )

    x_upper = max_value + max(0.01, max_value * 0.15)
    ax.set_xlabel("PR-AUC")
    ax.set_ylabel("Weights (α, β, γ)")
    ax.set_title("Weight Ablation Across PTG Parameter Settings")
    ax.set_xlim(0, x_upper)

    save_figure(fig, "fig4_weight_ablation.png")
    return True


def main():
    print(f"[info] Reading results from: {RESULTS_DIR}")
    print(f"[info] Saving figures to:   {FIGURES_DIR}")

    results = {
        "fig1_pr_curve": fig1_pr_curve(),
        "fig2_budget_curve": fig2_budget_curve(),
        "fig3_baseline_bars": fig3_baseline_bars(),
        "fig4_weight_ablation": fig4_weight_ablation(),
    }

    success_count = sum(results.values())
    print(f"\n[done] figure generation complete: {success_count}/{len(results)} succeeded")
    return results


if __name__ == "__main__":
    main()